# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0003_joinfriends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinfriends',
            name='email',
        ),
        migrations.RemoveField(
            model_name='joinfriends',
            name='emailall',
        ),
        migrations.RemoveField(
            model_name='joinfriends',
            name='friend',
        ),
        migrations.AddField(
            model_name='join',
            name='friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referer', to='joins.Join'),
        ),
        migrations.DeleteModel(
            name='JoinFriends',
        ),
    ]
